import {renderToStaticMarkup} from 'react-dom/server';
import {
  ActiveIcon,
  AddIcon,
  ArchiveIcon,
  CancelIcon,
  CalculatorIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  CloseTradeIcon,
  ChromeExtensionIcon,
  CrossIcon,
  CursorIcon,
  CopyIcon,
  DebugIcon,
  DeleteIcon,
  DisableIcon,
  DownloadIcon,
  EditIcon,
  EnsureTradeLogoBadgeIcon,
  EnsureTradeLogoIcon,
  InboxIcon,
  FastForwardIcon,
  GripDotsIcon,
  HistoryIcon,
  HomeIcon,
  InfoIcon,
  JournalIcon,
  LightbulbAddIcon,
  LightbulbIcon,
  MemoEditIcon,
  MessageIcon,
  MoreVertIcon,
  MoveIcon,
  NoteIcon,
  OpenTradeIcon,
  PanelDockIcon,
  PanelUndockIcon,
  PauseIcon,
  PinIcon,
  PlayCircleIcon,
  PlayIcon,
  RefreshIcon,
  ReferralIcon,
  RestoreIcon,
  UnpinIcon,
  SaveIcon,
  SaveScreenshotIcon,
  SessionIcon,
  SessionAddIcon,
  SessionEditIcon,
  SettingsIcon,
  ShareIcon,
  SignOutIcon,
  SitesIcon,
  StrategyIcon,
  StrategyAddIcon,
  TagsIcon,
  TargetIcon,
  TickIcon,
  TradesIcon,
  WarningIcon,
} from '../index';

const iconCases = [
  ['ActiveIcon', ActiveIcon],
  ['AddIcon', AddIcon],
  ['ArchiveIcon', ArchiveIcon],
  ['ArrowDownIcon', ArrowDownIcon],
  ['ArrowLeftIcon', ArrowLeftIcon],
  ['ArrowRightIcon', ArrowRightIcon],
  ['ArrowUpIcon', ArrowUpIcon],
  ['CloseTradeIcon', CloseTradeIcon],
  ['ChromeExtensionIcon', ChromeExtensionIcon],
  ['CrossIcon', CrossIcon],
  ['CursorIcon', CursorIcon],
  ['CopyIcon', CopyIcon],
  ['DebugIcon', DebugIcon],
  ['DeleteIcon', DeleteIcon],
  ['DisableIcon', DisableIcon],
  ['DownloadIcon', DownloadIcon],
  ['EditIcon', EditIcon],
  ['EnsureTradeLogoBadgeIcon', EnsureTradeLogoBadgeIcon],
  ['EnsureTradeLogoIcon', EnsureTradeLogoIcon],
  ['InboxIcon', InboxIcon],
  ['FastForwardIcon', FastForwardIcon],
  ['GripDotsIcon', GripDotsIcon],
  ['HistoryIcon', HistoryIcon],
  ['HomeIcon', HomeIcon],
  ['InfoIcon', InfoIcon],
  ['JournalIcon', JournalIcon],
  ['LightbulbAddIcon', LightbulbAddIcon],
  ['LightbulbIcon', LightbulbIcon],
  ['MemoEditIcon', MemoEditIcon],
  ['MessageIcon', MessageIcon],
  ['MoreVertIcon', MoreVertIcon],
  ['MoveIcon', MoveIcon],
  ['NoteIcon', NoteIcon],
  ['CancelIcon', CancelIcon],
  ['CalculatorIcon', CalculatorIcon],
  ['SaveIcon', SaveIcon],
  ['SaveScreenshotIcon', SaveScreenshotIcon],
  ['OpenTradeIcon', OpenTradeIcon],
  ['PanelDockIcon', PanelDockIcon],
  ['PanelUndockIcon', PanelUndockIcon],
  ['PauseIcon', PauseIcon],
  ['PinIcon', PinIcon],
  ['PlayCircleIcon', PlayCircleIcon],
  ['PlayIcon', PlayIcon],
  ['RefreshIcon', RefreshIcon],
  ['ReferralIcon', ReferralIcon],
  ['RestoreIcon', RestoreIcon],
  ['SessionIcon', SessionIcon],
  ['SessionAddIcon', SessionAddIcon],
  ['SessionEditIcon', SessionEditIcon],
  ['SettingsIcon', SettingsIcon],
  ['ShareIcon', ShareIcon],
  ['SignOutIcon', SignOutIcon],
  ['SitesIcon', SitesIcon],
  ['StrategyIcon', StrategyIcon],
  ['StrategyAddIcon', StrategyAddIcon],
  ['TagsIcon', TagsIcon],
  ['TargetIcon', TargetIcon],
  ['TickIcon', TickIcon],
  ['TradesIcon', TradesIcon],
  ['UnpinIcon', UnpinIcon],
  ['WarningIcon', WarningIcon],
] as const;

describe('icons', () => {
  it.each(iconCases)('%s renders an svg element', (_label, Icon) => {
    const html = renderToStaticMarkup(<Icon />);
    expect(html).toMatch(/<svg[\s>]/);
  });
});
